name: Docker image
env:
  platforms: linux/amd64,linux/arm64
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        alpine_version: ["3.18"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up multiarch
      uses: docker/setup-qemu-action@v1
    - name: Set up BuildX
      uses: docker/setup-buildx-action@v1
    - name: Docker login
      run: |
        echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
        echo ${DOCKER_HUB_KEY} | docker login -u cmbdevopsbot --password-stdin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_HUB_KEY: ${{ secrets.DOCKER_HUB_KEY }}
    - name: Build and push Docker image
      run: | 
        docker buildx build --platform $platforms --push . --file Dockerfile --build-arg ALPINE_VERSION=${{ matrix.alpine_version }} --tag ghcr.io/combinationab/network-tools-alpine/network-tools-alpine:${{ matrix.alpine_version }} --tag combination/network-tools-alpine:${{ matrix.alpine_version }}
